name: Build and Deploy Game

on:
  workflow_call:
    inputs:
        debug:
            description: Build Debug configuration?
            type: boolean
            required: true
            default: false
        qa:
            description: Build QA configuration?
            type: boolean
            required: true
            default: true
        release:
            description: Build Release configuration?
            type: boolean
            required: true
            default: true

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .

permissions:
  contents: read

jobs:
  Build_and_Deploy_Game:
    runs-on: windows-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Print args
      run: echo "${{ inputs.debug }} ${{ inputs.qa }} ${{ inputs.release }} ${{ github.event.inputs.debug }} ${{ github.event.inputs.qa }} ${{ github.event.inputs.release }}"

    - if: ${{ github.event.inputs.debug == 'true' }}
      name: Events debug
      run: echo "events debug true"

    - if: ${{ github.event.inputs.qa == 'true' }}
      name: Events qa
      run: echo "events qa true"

    - if: ${{ github.event.inputs.release == 'true' }}
      name: Events release
      run: echo "events release true"

    - if: ${{ inputs.debug }}
      name: Inputs debug
      run: echo "inputs debug true"

    - if: ${{ inputs.qa }}
      name: Inputs qa
      run: echo "inputs qa true"

    - if: ${{ inputs.release }}
      name: Inputs release
      run: echo "inputs release true"

    - if: ${{ github.event.inputs.debug == 'true' }} || ${{ inputs.debug }} 
      name: Build Debug Configuration
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=Debug ${{env.SOLUTION_FILE_PATH}}

    - if: ${{ github.event.inputs.qa == 'true' }} || ${{ inputs.qa }} 
      name: Build QA Configuration
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=QA ${{env.SOLUTION_FILE_PATH}}

    - if: ${{ github.event.inputs.release == 'true' }} || ${{ inputs.release }} 
      name: Build Release Configuration
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=Release ${{env.SOLUTION_FILE_PATH}}
  
    - name: Deploy Game
      uses: actions/upload-artifact@v3
      with:
        name: Game
        path: ${{env.SOLUTION_FILE_PATH}}\bin
        retention-days: 7
