name: Create Package

on:
  workflow_dispatch:
    inputs:
        debug:
            description: Build Debug configuration?
            type: boolean
            required: true
            default: false
        qa:
            description: Build QA configuration?
            type: boolean
            required: true
            default: true
        release:
            description: Build Release configuration?
            type: boolean
            required: true
            default: true

jobs:
  Create_Package:
    uses: ./.github/workflows/BuildAndDeployGame.yml
    with:
        debug: ${{ env.INPUT_DEBUG }}
        qa: ${{ env.INPUT_QA }}
        release: ${{ env.INPUT_RELEASE }}
