name: Deploy Latest Main

on:
  push:
    branches: [ main ]

jobs:
  Deploy_Latest_Main:
    uses: ./.github/workflows/BuildAndDeployGame.yml
    with:
        debug: true
        qa: true
        relase: true
